package com.smallprintjobs.Beans;
// Generated 01-feb-2017 21:02:19 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;


/**
 * Empresas generated by hbm2java
 */
//@Entity
//@Table(name="EMPRESAS")
public class Empresas implements java.io.Serializable {

//	@Id
//	@Column(name="id_emp")
	private Integer idEmp;
	private String cif;
	private String nombre;
	private String sector;
	private String direccion;
	private String localidad;
	private String provincia;
	private String pais;
	private String codPostal;
	private String sede;
	private String web;
	private Set comentarioses = new HashSet(0);

	public Empresas() {
	}

	public Empresas(String cif, String nombre, String sector, String direccion, String localidad, String provincia,
			String pais, String codPostal, String sede, String web, Set comentarioses) {
		this.cif = cif;
		this.nombre = nombre;
		this.sector = sector;
		this.direccion = direccion;
		this.localidad = localidad;
		this.provincia = provincia;
		this.pais = pais;
		this.codPostal = codPostal;
		this.sede = sede;
		this.web = web;
		this.comentarioses = comentarioses;
	}

	public Integer getIdEmp() {
		return this.idEmp;
	}

	public void setIdEmp(Integer idEmp) {
		this.idEmp = idEmp;
	}

	public String getCif() {
		return this.cif;
	}

	public void setCif(String cif) {
		this.cif = cif;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getSector() {
		return this.sector;
	}

	public void setSector(String sector) {
		this.sector = sector;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	public String getCodPostal() {
		return this.codPostal;
	}

	public void setCodPostal(String codPostal) {
		this.codPostal = codPostal;
	}

	public String getSede() {
		return this.sede;
	}

	public void setSede(String sede) {
		this.sede = sede;
	}

	public String getWeb() {
		return this.web;
	}

	public void setWeb(String web) {
		this.web = web;
	}

	public Set getComentarioses() {
		return this.comentarioses;
	}

	public void setComentarioses(Set comentarioses) {
		this.comentarioses = comentarioses;
	}

}
