package com.smallprintjobs.Beans;


//package modelo;
// Generated 01-feb-2017 21:02:19 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

//import javax.persistence.Column;
//import javax.persistence.GeneratedValue;
//import javax.persistence.Id;
//
//import org.hibernate.annotations.Entity;
//import org.hibernate.annotations.Table;




/**
 * Usuario generated by hbm2java
 */
//@Entity
//@Table(name="USUARIOS")
public class Usuario implements java.io.Serializable {

//	@Id
//	@Column(name="ID_USER")
//	@GeneratedValue
	private Integer id_user;
	private String alias;
	private String surname;
	private String name;
	private Date birth;
	private String sex;
	private String degrees;
	private String password;
	private String mail;
	private Boolean enable;
	private Boolean mailVerify;

	public Usuario() {
	}

	public Usuario(String alias, String surname, String name, Date birth, String sex, String degrees, String password,
			String mail, Boolean enable, Boolean mailVerify) {
		this.alias = alias;
		this.surname = surname;
		this.name = name;
		this.birth = birth;
		this.sex = sex;
		this.degrees = degrees;
		this.password = password;
		this.mail = mail;
		this.enable = enable;
		this.mailVerify = mailVerify;
	}

	public Integer getId_user() {
		return this.id_user;
	}

	public void setId_user(Integer id_user) {
		this.id_user = id_user;
	}

	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getBirth() {
		return this.birth;
	}

	public void setBirth(Date birth) {
		this.birth = birth;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getDegrees() {
		return this.degrees;
	}

	public void setDegrees(String degrees) {
		this.degrees = degrees;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public Boolean getEnable() {
		return this.enable;
	}

	public void setEnable(Boolean enable) {
		this.enable = enable;
	}

	public Boolean getMailVerify() {
		return this.mailVerify;
	}

	public void setMailVerify(Boolean mailVerify) {
		this.mailVerify = mailVerify;
	}

}
