package com.smallprintjobs.Modelo.impl;
// Generated 01-feb-2017 21:02:19 by Hibernate Tools 5.2.0.CR1

import java.util.Date;



/**
 * Comentarios generated by hbm2java
 */
//@Entity
//@Table(name="COMENTARIOS")
public class ComentariosDaoImpl implements java.io.Serializable {

//	@Id
//	@Column(name="id_com")
	private Integer idCom;
	private Integer id_emp;
	private Integer id_user;
	private EmpresasDaoImpl empresas;
	private String departamento;
	private String proyecto;
	private Date fechaCom;
	private Date fechaIniPro;
	private Date fechaFinProyecto;
	private String comentario;
	private Integer valoracion;

	public ComentariosDaoImpl() {
	}



	public ComentariosDaoImpl(EmpresasDaoImpl empresas,Integer id_emp, Integer id_user, String departamento, String proyecto, Date fechaCom,
			Date fechaIniPro, Date fechaFinProyecto, String comentario, Integer valoracion) {
		this.empresas = empresas;
		this.id_emp = id_emp;
		this.id_user = id_user;
		this.departamento = departamento;
		this.proyecto = proyecto;
		this.fechaCom = fechaCom;				//fecha comentario
		this.fechaIniPro = fechaIniPro;
		this.fechaFinProyecto = fechaFinProyecto;
		this.comentario = comentario;
		this.valoracion = valoracion;
	}

	public Integer getIdCom() {
		return this.idCom;
	}

	public void setIdCom(Integer idCom) {
		this.idCom = idCom;
	}

	public EmpresasDaoImpl getEmpresas() {
		return this.empresas;
	}

	public void setEmpresas(EmpresasDaoImpl empresas) {
		this.empresas = empresas;
	}

	public Integer getId_emp() {
		return this.id_emp;
	}

	public void setId_emp(Integer id_emp) {
		this.id_emp = id_emp;
	}	
		
	public Integer getId_user() {
		return this.id_user;
	}

	public void setId_user(Integer id_user) {
		this.id_user = id_user;
	}

	public String getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(String departamento) {
		this.departamento = departamento;
	}

	public String getProyecto() {
		return this.proyecto;
	}

	public void setProyecto(String proyecto) {
		this.proyecto = proyecto;
	}

	public Date getFechaCom() {
		return this.fechaCom;
	}

	public void setFechaCom(Date fechaCom) {
		this.fechaCom = fechaCom;
	}

	public Date getFechaIniPro() {
		return this.fechaIniPro;
	}

	public void setFechaIniPro(Date fechaIniPro) {
		this.fechaIniPro = fechaIniPro;
	}

	public Date getFechaFinProyecto() {
		return this.fechaFinProyecto;
	}

	public void setFechaFinProyecto(Date fechaFinProyecto) {
		this.fechaFinProyecto = fechaFinProyecto;
	}

	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	public Integer getValoracion() {
		return this.valoracion;
	}

	public void setValoracion(Integer valoracion) {
		this.valoracion = valoracion;
	}

}
